### ISSUE TITLE
Blaseball Game Cards 4 to Line when betting 3-4 digit bets.

### ISSUE THREAD

**Issue by PixelDrifter** [holmesmr/Blaseball-Userstyles#2]
On my Laptop in 1920x1080 resolution when I place large bets on games the cards will be 4 to a line, rather than 5 to a line in Firefox on 100% zoom. Problem is currently being salved with 70% zoom.

**Comment by holmesmr** [comment]
Will assume this is no longer applicable to the latest version. Feel free to open a new issue if you still have this problem!
