### ISSUE TITLE
windows 10 emoji fix suggestion

### ISSUE THREAD

**Issue by rwiiebe** [holmesmr/Blaseball-Userstyles#3]
Hi there,

I would like to suggest adding the classes _.Navigation-FavoriteTeamEmoji, .Leaderboard-Team-Emoji,_ to the emoji fix.

Another suggestion: I was able to force the emojis to display the "newest"/proper windows 10 emoji using the style _font-family:"Segoe UI Emoji"_ to force them the use the newer emoji font, which would be a better fix for people with this font installed.

Thanks for the inspo to do custom styles, the missing emoji were REALLY bugging me! 🗣

**Comment by holmesmr** [comment]
Thanks for your suggestion! I've incorporated this into the latest version. Apologies for not doing this last season!
